/* ============================================================
   UNIVERSITY DETAILS — ENGLISH descriptions.
   Keyed by `short` from catalog.jsx. Loaded after uni-data.js.
   uni-page.jsx picks this when __EA_LANG === 'en'; if a `short`
   is missing here, it falls back to a localized generated blurb.
   Only the `about` field is translated (facts come from uni-data.js).
   ============================================================ */
var EA_UNI_DETAILS_EN = {
  /* ========== ITALY ========== */
  "PoliMi":   { about: "Italy’s largest technical university and its leading school of engineering, architecture and design — consistently in the world’s top 20 for design and architecture." },
  "Bocconi":  { about: "A private Milan university and one of Europe’s strongest business schools. Economics, finance, management and law, with a powerful alumni network in global corporations." },
  "UniBo":    { about: "The oldest university in the Western world, running continuously since 1088. Strong in economics, law and the humanities, with campuses in five cities across the region." },
  "Sapienza": { about: "One of Europe’s largest universities and Rome’s main public institution. A world leader in classics and archaeology, with a wide choice of English-taught programs." },
  "UniPD":    { about: "One of the world’s oldest universities — Galileo once taught here. Strong in medicine, psychology and engineering, with a well-developed scholarship system for international students." },
  "CaFosc":   { about: "A university in the heart of Venice and Italy’s first school of commerce. Known for economics, languages and Asian studies; classes are held in historic palazzi on the canals." },
  "LUISS":    { about: "A prestigious private university in Rome backed by Confindustria, the Italian industry association. Law, political science and business, with close ties to employers." },
  "PoliTO":   { about: "A leading engineering school in Turin — home of FIAT and the Italian auto industry. Strong in automotive, aerospace and computer engineering." },
  "UniMi":    { about: "‘La Statale’, the largest university in Milan. A broad range of programs from law and medicine to the natural sciences; a member of the prestigious LERU research league." },
  "UniTO":    { about: "One of Italy’s largest classical universities. Strong in medicine, law and economics; its alumni include Nobel laureates and two of the country’s presidents." },
  "UniPI":    { about: "A historic university in Tuscany and Galileo Galilei’s alma mater. Today one of Italy’s strongest centres for computer science and physics." },
  "TorVerg":  { about: "A modern campus university in southern Rome. Strong in medicine, engineering and economics, and one of Italy’s leaders in English-taught programs." },
  "UniFI":    { about: "The classical university of Florence — the capital of the Renaissance. Especially strong in architecture, design, art history and agricultural sciences." },
  "UniSI":    { about: "One of Europe’s oldest universities, in the Tuscan town of Siena. A compact ‘university town’ with strong medicine, biotechnology and economics." },
  "UniPV":    { about: "An ancient university in Lombardy with an Oxbridge-style college system. Known for medicine and engineering — Alessandro Volta studied here." },
  "UniTN":    { about: "One of the highest-rated universities in Italy for teaching quality, regularly ranked #1 among the country’s mid-sized universities. Strong computer and cognitive science, with a campus in the Alps." },
  "UniTS":    { about: "A university in the port city of Trieste — Italy’s scientific capital, with the country’s largest concentration of research centres. Strong in physics and engineering." },
  "UniBS":    { about: "A public university in Lombardy with strong medicine and engineering. Brescia is an industrial hub, giving students direct access to internships." },
  "UniPR":    { about: "One of the world’s oldest universities, dating back to the 10th century. Known for medicine, pharmacy and food science — Parma is Italy’s gastronomic capital." },
  "LUMSA":    { about: "A Catholic private university in Rome, the city’s second-oldest non-state institution. Education, law and communications, with small groups and personal mentoring." },
  "Marang":   { about: "The legendary Milan school of fashion and design that produced Domenico Dolce and Franco Moschino. Campuses in the world’s fashion capitals and close ties to fashion houses." },
  "IULM":     { about: "A Milan university of communications, marketing and media. One of Italy’s main centres for training PR, translation and creative-industry specialists." },
  "UniMiB":   { about: "A young, dynamic Milan university with a modern campus in the Bicocca district. Strong in medicine, psychology and data science." },
  "UniGE":    { about: "A historic university in Italy’s largest port. Strong in marine engineering, robotics and economics, with campuses along the Ligurian coast." },
  "Roma3":    { about: "The youngest of Rome’s three public universities, which quickly became one of the country’s notable institutions. Strong in law, architecture and political science." },
  "UniPA":    { about: "Sicily’s main university, in Palermo. A wide choice of programs at some of the lowest tuition and living costs in Western Europe." },
  "UniME":    { about: "An old Sicilian university by the Strait of Messina. Strong in medicine, veterinary science and law, with affordable tuition and living costs." },
  "UniCT":    { about: "Sicily’s oldest university, at the foot of Mount Etna. Strong medicine and engineering — Catania is southern Italy’s main tech hub (‘Etna Valley’)." },
  "UniSA":    { about: "Heir to the medieval Salerno medical school — Europe’s first. A modern campus near Salerno, strong in engineering and computer science." },
  "UniCAS":   { about: "A compact public university between Rome and Naples. Affordable, with strong engineering and sports science and a welcoming environment for international students." },
  "UniUD":    { about: "A university in north-eastern Italy near Austria and Slovenia. Strong in business, winemaking and engineering, in the high-quality-of-life Friuli region." },
  "UniCamp":  { about: "A public university named after architect Luigi Vanvitelli in the Naples region. Known for medicine and architecture, with some of the lowest tuition in Italy." },
  "UniBa":    { about: "A large university in the capital of Apulia in southern Italy. A wide choice of fields — from law to agricultural sciences — at very affordable cost." },
  "UNIVPM":   { about: "A polytechnic university of the Marche region in seaside Ancona. Strong in engineering, medicine and economics, with small groups and a practical focus." },
  "LinkCU":   { about: "A private Rome university with an international focus and Foundation programs. Business, international relations and cinema, taught in English." },
  "RUFA":     { about: "The Rome University of Fine Arts — painting, graphic design, film and game art. Studios in Rome’s historic centre, taught by working artists." },
  "LUM":      { about: "A private university in Apulia with programs in business, law and medicine. Flexible admission and Foundation programs for international students." },

  /* ========== USA ========== */
  "Roosevelt": { about: "A university in a skyscraper in the heart of Chicago, named after Franklin and Eleanor Roosevelt. Generous merit scholarships for international students; strong in business and the performing arts." },
  "Bellevue":  { about: "One of Washington State’s largest colleges, right across from the Microsoft and Amazon campuses. A popular 2+2 route: two years here, then transfer to a top university." },
  "LaSalle":   { about: "A Catholic university in Philadelphia with a century and a half of history. Known for nursing, business and communications; the campus is 15 minutes from downtown." },
  "K-Zoo":     { about: "One of the oldest liberal arts colleges in the Midwest. Small classes, required internships and study abroad; a high share of graduates go on to master’s and PhD programs." },
  "Westcliff": { about: "A private university in Irvine, California — one of the safest cities in the US. Business and IT, flexible study formats and affordable-for-California tuition." },
  "UB":        { about: "The flagship and largest campus of New York’s SUNY system, a member of the prestigious AAU research association. Strong in engineering, medicine and computer science." },
  "UE":        { about: "A private university in Indiana with small classes and its own campus in England (Harlaxton College). Strong in engineering, physical therapy and theatre." },
  "DePaul":    { about: "The largest Catholic university in the US, in downtown Chicago. One of the country’s best for game design and film; a strong business school and computer science." },
  "Rowan":     { about: "A fast-growing public university in New Jersey, an hour from Philadelphia. A strong engineering school and two medical schools — rare for a university of its size." },
  "HarrisU":   { about: "A young STEM university in Pennsylvania’s capital. Science and technology only: data analytics, cybersecurity, biotech; practice- and employment-focused." },
  "UST":       { about: "A Catholic university in Houston’s museum district. Small classes, strong business and pre-med preparation; next to the world’s largest medical center." },
  "ASU":       { about: "One of the largest universities in the US, named the country’s most innovative university for years running. Top-tier engineering, business and journalism; a huge range of programs." },
  "CalState":  { about: "The largest public university system in the US — 23 campuses across California. Practice-oriented programs at affordable in-state cost." },
  "SJSU":      { about: "The oldest public university on the West Coast — in the heart of Silicon Valley. #1 in the US for graduates hired by Apple, Cisco and other tech giants." },
  "GGU":       { about: "A university in downtown San Francisco specialising in law, taxation and business for working professionals. Evening and flexible formats." },
  "MU":        { about: "A Catholic university in Arlington, Virginia — across the river from Washington. Strong in nursing, cybersecurity and interior design; internships in the capital." },
  "Adelphi":   { about: "Long Island’s first private university, 40 minutes from Manhattan. A green arboretum campus; strong in nursing, psychology and social work." },
  "UC":        { about: "The birthplace of co-op education: paid internships have been built into study since the 19th century. Top engineering, music (CCM) and design — DAAP is world-ranked." },
  "Temple":    { about: "A large research university in Philadelphia with some of the most affordable tuition among Northeast urban schools. Strong in business, law, film and media." },
  "Drexel":    { about: "A technology university in Philadelphia famous for its co-op system: up to three paid 6-month internships during the bachelor’s. Strong in engineering and design." },
  "Suffolk":   { about: "A university in the heart of Boston, opposite the State House. Known for law and business; internships a stone’s throw away in the city’s offices and courts." },
  "Pace":      { about: "A university with a campus by Wall Street in New York. A leader in finance and audit internships; strong in business, computer science and the performing arts." },
  "UArizona":  { about: "Arizona’s flagship university and an AAU member. A world leader in astronomy and space research — it takes part in NASA missions; strong in optics and medicine." },
  "FIU":       { about: "One of the largest public universities in the US, in Miami. Strong in international business, hospitality and engineering; the country’s most international city." },
  "UConn":     { about: "Connecticut’s flagship university, in the top 30 public schools in the US. Strong in business, engineering and pharmacy; between New York and Boston." },
  "Clarkson":  { about: "A private technology university in upstate New York. One of the best for return on a degree: engineering graduates quickly reach high salaries." },
  "ColChic":   { about: "The largest arts college in the US, in downtown Chicago. Film, music, fashion, game design, journalism; taught by working industry professionals." },
  "NYFA":      { about: "A film academy with campuses in New York and Los Angeles. Learning ‘through the camera’ from day one: directing, acting, animation and producing." },
  "Webster":   { about: "A university from St. Louis with campuses worldwide — from Vienna to Bangkok. Strong in international relations, business and media; you can switch campuses mid-study." },
  "Simmons":   { about: "A Boston university next to the Longwood medical cluster. Famous for nursing, nutrition and library science; the bachelor’s is women’s, the master’s is co-ed." },
  "FloridaTech": { about: "A technology university on Florida’s ‘Space Coast’, founded by NASA scientists at the dawn of the space age. Aerospace engineering, aviation, oceanography." },
  "NAU":       { about: "A young private university in Houston with some of the most affordable tuition in Texas. Computer science, business and education; a large international community." },
  "Radford":   { about: "A public university in the mountains of Virginia. Affordable, strong in nursing, forensic science and business; a safe campus town." },
  "Concord":   { about: "A small public university in West Virginia, known as ‘the campus beautiful’ for its mountain views. Low cost and personal attention from faculty." },
  "UAlbany":   { about: "One of the four flagship campuses of the SUNY system — in New York’s capital. Strong in criminology, public administration and cybersecurity." },
  "CWU":       { about: "A public university in central Washington. Known for aviation (its own flight fleet), music and business; a low cost of living." },
  "ConnColl":  { about: "A selective liberal arts college in New England with an arboretum campus on the sound. Generous financial aid, small classes and funded internships." },
  "SFBU":      { about: "A non-profit university in the San Francisco Bay Area, next to Silicon Valley. Computer science and business; substantial scholarships for nearly all admitted students." },
  "SCSS":      { about: "A university in Los Angeles with bachelor’s and master’s programs in business. Admission details are available at an Elite Academy consultation." },
  "DeAnza":    { about: "One of the best community colleges in the US — in Cupertino, Apple’s hometown. California’s leader in transfers to UC universities, including Berkeley and UCLA." },
  "GreenRiver":{ about: "A college near Seattle, one of the most international-student-friendly in the US. A well-established route to transfer to universities after two years." },
  "SCC":       { about: "A college in the heart of Seattle on Capitol Hill. A convenient start for the 2+2 route and English programs; the city is home to Amazon, Boeing and Starbucks." },
  "SMC":       { about: "The #1 college in the US for transfers to UCLA and USC. A campus 15 minutes from the ocean; strong in film, design and business." },
  "LACC":      { about: "A historic city college of Los Angeles in the Hollywood area. An affordable entry into California’s higher-education system; a well-known theatre school." },
  "CCC":       { about: "A network of seven city colleges of Chicago — one of the largest community-college districts in the US. Low cost and transfer agreements with Illinois universities." },
  "LWIT":      { about: "A technical institute in Kirkland, a Seattle suburb near the Google and Microsoft offices. Applied IT programs and an applied bachelor’s degree." },
  "CCSF":      { about: "San Francisco’s main city college. A huge choice of programs and a well-established transfer to California universities after two years." },
  "CSI":       { about: "A career school in Chicago with short, hands-on IT and business programs. A fast, low-cost way to earn a US certificate and experience." },

  /* ========== USA — Shorelight/ApplyWave partners ========== */
  "Rutgers":   { about: "New Jersey’s flagship university, in the US top 50 (US News) — 30 minutes from New York. An elite AAU member; strong in business, pharmacy and medicine." },
  "SBU":       { about: "SUNY’s flagship research university on Long Island (#59 US News). An AAU member with Nobel laureates on faculty; strong in IT, physics and medicine." },
  "Tulane":    { about: "A prestigious research university in New Orleans (#69 US News). One of the leading schools in the US South; strong in business, medicine and international relations." },
  "Villanova": { about: "An elite Catholic university near Philadelphia (#57 US News). Villanova School of Business is in the US top 20; strong in engineering and law with high employment rates." },
  "UIC":       { about: "Chicago’s largest public university (#84 US News). A powerful medical and engineering campus in the heart of America’s third city; affordable for its scale." },
  "Auburn":    { about: "Alabama’s flagship technical university (#102 US News). One of the largest engineering faculties in the South; strong in aerospace engineering and veterinary science." },
  "Gonzaga":   { about: "A Jesuit university in Spokane (#102 US News). Consistently in the West Coast’s top 5 MBAs; strong in law and business; known for its powerful basketball team." },
  "UCF":       { about: "One of the largest universities in the US, in sunny Orlando (#117 US News). Key employers are NASA, Disney and Universal; a leader in simulation, aerospace and hospitality." },
  "UofSC":     { about: "South Carolina’s flagship (#127 US News) with one of the oldest international-business faculties in the US. An Honors College and generous merit scholarships for international students." },
  "LSU":       { about: "Louisiana’s flagship public university (#169 US News). A leading research centre for the US oil and gas industry; strong in chemical engineering and agronomy." },
  "KU":        { about: "Kansas’s flagship university and a member of the AAU and Big 12. The region’s best pharmacy school (PharmD); strong in business and law; one of the most beautiful campuses in the US." },
  "SeattleU":  { about: "A Jesuit university in downtown Seattle (#151 US News). Partnerships with Amazon, Boeing and Microsoft; strong in nursing, business and law; small groups and a personal approach." },
  "MontanaSt": { about: "Montana’s main research and technical university, surrounded by the Rocky Mountains. Strong in engineering and environmental science; one of the most scenic campuses in the US." },
  "NewSchool": { about: "A progressive university in Greenwich Village, New York. Parsons School of Design is one of the world’s three best design colleges; strong in media, architecture and social sciences." },
  "NewHaven":  { about: "A private university in New Haven, Connecticut (30 min from New York). #1 in the US for forensics and criminal justice; strong in cybersecurity." },
  "AU":        { about: "A prestigious private university in the heart of Washington. Strong in international relations, political science and business; direct access to government, NGOs and embassies." },
  "JHU":       { about: "America’s first research university (#7 US News, QS #16). A world leader in medicine, engineering and public health; master’s programs available via Shorelight." },
  "UVA":       { about: "One of the best public universities in the US (#26 US News, QS #201), founded by Thomas Jefferson. Master’s programs in business, law and engineering available via Shorelight." },
  "Pepperdine": { about: "An elite private university on the Pacific coast in Malibu (#84 US News). In the top 50 MBA programs; strong in business, law and international relations; a stunning campus." },
  "UUtah":     { about: "Utah’s flagship university, the birthplace of Adobe and WordPerfect (#151 US News). At the centre of ‘Silicon Slopes’ — the #2 concentration of tech companies in the US after Silicon Valley." },
  "UTSA":      { about: "A large public university in San Antonio — one of the fastest-growing schools in the US. A US Department of Defense cybersecurity centre; strong in business and IT." },
  "UDayton":   { about: "A Catholic research university in Dayton (#143 US News). A powerful engineering school and partnerships with NASA and the US Air Force; a research park right on campus." },
  "Pacific":   { about: "California’s oldest chartered university (#139 US News). Strong in dentistry, pharmacy and business; small groups and a personal approach in a big state." },
  "UNR":       { about: "Nevada’s flagship university in the casino-and-startup city of Reno (#192 US News). A growing IT cluster; affordable cost of living and tuition; no state income tax." },
  "UMassB":    { about: "A public university right in Boston, by the ocean (#213 US News). An affordable entry into the Boston ecosystem with Amazon, Microsoft and hundreds of biotech firms nearby." },
  "MissouriST": { about: "Missouri’s leading technical university, specialising in STEM. In the US top 10 engineering schools by ROI; strong in mining engineering, nuclear physics and IT." },
  "ClevSt":    { about: "An urban public university in downtown Cleveland. Partnerships with the Cleveland Clinic (US top-2 in cardiology); strong in business and law." },
  "RMU":       { about: "A private, business-focused university near Pittsburgh. Specialises in business education and IT; high employment thanks to ties with corporate Pittsburgh." },
  "Belmont":   { about: "A private university in America’s music capital — Nashville. The country’s best music-business program; also strong in entrepreneurship, healthcare and film." },
  "OCU":       { about: "A private university in Oklahoma City with strong traditions in the performing arts, law and business. An atmospheric campus in a historic district and a personal approach." },
  "UWyo":      { about: "Wyoming’s flagship university in the Rocky Mountains (#222 US News). One of the most affordable public schools for international students; strong in mining engineering and agribusiness." },
  "UPortland": { about: "A Jesuit university on a hill above Portland with views of Mount Hood. An atmospheric green campus; strong in nursing, engineering and business; partnerships with Nike and Intel." },
  "RuCamden":  { about: "A Rutgers campus (US top 50) in Camden, opposite Philadelphia. Full Rutgers degrees at more affordable prices; strong in business, criminal justice and law." },
  "UtahTech":  { about: "A public university in southern Utah, in the scenic canyon landscape of St. George. Some of the lowest tuition in the US; hands-on IT and business programs." },
  "UWEC":      { about: "A UW-system public university in Eau Claire with a scenic campus. One of the most international-student-friendly schools in the Midwest; strong in business and journalism." },
  "UWGB":      { about: "A University of Wisconsin school in Green Bay — an affordable start in American education. Strong in ecology, business and cross-cultural communication; small groups." },
  "UWWW":      { about: "One of the largest UW-system campuses with a strong business faculty. Great value for money; 80+ programs, including early-format MBAs." },
  "UWRF":      { about: "A UW-system public campus in scenic River Falls. Some of the lowest tuition in the US; strong in agribusiness, communications and education." },
  "UWSup":     { about: "The most affordable UW-system campus, on the shores of Lake Superior. Small groups and a personal approach; strong in transport logistics and marine technology." },
  "UWSP":      { about: "A UW-system campus in Stevens Point — a leader in environmental programs. One of America’s ‘green’ universities; strong in natural-resource management and business." },
  "UISG":      { about: "An Illinois public university in the state capital, Springfield. Online and on-campus study; strong in public administration, business and educational technology." },
  "UAF":       { about: "Alaska’s flagship research university in arctic Fairbanks. A world centre for Arctic and aurora research; strong in engineering, geophysics and Indigenous studies." },
  "Bellarmine": { about: "A Catholic university in Louisville, Kentucky. A personal approach; strong in business, nursing and psychology; scholarships from 50% for international students." },
  "CarrollU":  { about: "A private university near Milwaukee (Waukesha, Wisconsin). Strong in psychology, sports science and business; one of Wisconsin’s leaders in graduate employment." },
  "DeanC":     { about: "A cozy private college an hour from Boston. Ideal for adapting to the American system; offers a two-year foundation and transfer to larger universities." },
  "Eureka":    { about: "One of Illinois’s oldest liberal arts colleges, Ronald Reagan’s alma mater. Free tuition on summer programs; a personal approach and active student life." },
  "Felician":  { about: "A Catholic university in New Jersey, 20 minutes from New York. Strong in nursing, education and business; excellent value for the region." },
  "Hanover":   { about: "One of Indiana’s oldest private colleges, on the banks of the Ohio River. Very small groups (12–15 students), a scenic campus; merit scholarships up to $24,000 a year." },
  "Hartwick":  { about: "An old liberal arts college in the Catskill Mountains, New York. A unique one-month January J-Term; strong in the natural sciences, management and anthropology." },
  "Hiram":     { about: "A liberal arts college in rural Ohio with an innovative curriculum. A unique format: 12 weeks of core classes + 3 intensive project weeks; scholarships up to 100%." },
  "HolyCross": { about: "A small Catholic college next to Notre Dame (Indiana). It draws on the resources of neighbouring Notre Dame; strong in theology and the humanities; a cozy campus." },
  "IllinoisWes": { about: "An elite liberal arts college in Bloomington, Illinois. One of the highest employment rates among small colleges; strong in business, the performing arts and the sciences." },
  "Lakeland":  { about: "A private university by Lake Michigan in Wisconsin. Affordable prices and flexible online programs; one of the first in the US to offer fully online degrees." },
  "LewisU":    { about: "A De La Salle Christian Brothers university near Chicago (Romeoville). A regional leader in aviation programs; strong in cybersecurity, nursing and business." },
  "McMurry":   { about: "A Methodist university in Abilene, Texas. A small campus with a personal approach; strong in business, education and the performing arts; scholarships up to $18,000." },
  "MGHIHP":    { about: "A specialised health institute of the Mass General Brigham system (Harvard-affiliated). Master’s/PhD programs in physical therapy, speech pathology and nursing." },
  "Moravian":  { about: "One of the oldest universities in the US (1742) in Bethlehem, Pennsylvania. Combines liberal education and professional training; strong in business, psychology and music." },
  "MtStMary":  { about: "The second-oldest Catholic university in the US, in the mountains of Maryland. Strong in business, nursing and the liberal arts; an on-campus seminary gives it a unique character." },
  "OhioWes":   { about: "A prestigious Ohio liberal arts college with the OWU Connection program — a required practical project abroad or in business. Strong in the natural sciences and politics." },
  "PalmBeach": { about: "A Christian university on Florida’s Atlantic coast in West Palm Beach. A sunny campus; strong in business, music and criminal justice; merit scholarships up to $20,000." },
  "RandolphC": { about: "A small liberal arts college in Lynchburg, Virginia. One of the few remaining true liberal arts colleges; a personal approach and 100% financial transparency." },
  "SaintMaryMN": { about: "A Catholic university in scenic Winona on the Mississippi River, Minnesota. Strong in business, education and the arts; campuses in Winona and Minneapolis–St. Paul." },
  "SalveRegina": { about: "A Catholic university in historic Newport, Rhode Island, by the ocean. Strong in criminal justice, business and international relations; unique Gilded Age mansions serve as buildings." },
  "Schreiner": { about: "A small private university in the Texas Hill Country. One of the few US schools with a special program for students with dyslexia and ADHD; scholarships up to $16,000." },
  "StBon":     { about: "A Franciscan university by a state forest in western New York. Strong in journalism (CNN, NBC alumni), business and education; a cozy campus with a basilica chapel." },
  "StCatherine": { about: "One of the largest Catholic universities for women in the US (St. Paul, Minnesota). Strong in health, education and business; joint programs with surrounding universities." },
  "StMaryCA":  { about: "A Catholic liberal arts college in the foothills near San Francisco. The Jan Term program — a month immersed in one subject or an international expedition; strong in business and education." },
  "StThomasAQ": { about: "A Catholic university in suburban New York (Sparkill, 17 miles to Manhattan). Direct access to internships in New York; strong in business and education." },
  "TrinityCC": { about: "A Reformed Christian college near Chicago (Palos Heights, Illinois). Strong in education, business and the performing arts; direct access to the Chicago economy." },
  "UCharleston": { about: "A private university in Charleston, the capital of West Virginia. Hands-on programs in aviation, pharmacy and business; generous scholarships for international students." },
  "UDubuque":  { about: "A private university in Dubuque, Iowa, by the Mississippi River. Aviation programs (its own aircraft fleet), theology and business; affordable Midwest prices." },
  "UMountUnion": { about: "A small private university in Alliance, Ohio. Active student life and over 100 clubs; strong in education, sport and entrepreneurship; merit scholarships up to $22,000." },
  "UNE":       { about: "A private university on the Atlantic coast of Maine with two campuses. The best osteopathic medical school in New England; strong in physical therapy and marine biology." },
  "URedlands": { about: "A private liberal arts university at the foot of the San Bernardino Mountains, California. The unique Johnston Center lets students design their own program; strong in geography and GIS." },
  "USaintMary": { about: "A small Catholic university in Leavenworth, Kansas. One of the most affordable private schools in the US; strong in business, education and nursing; merit scholarships up to $16,000." },
  "VirginiaWes": { about: "A Methodist liberal arts college in Norfolk on the Atlantic coast. Strong in business, criminal justice and education; a cozy campus ten minutes from the beach." },
  "WashJeff":  { about: "One of the oldest universities in the US (1781) near Pittsburgh. Alumni include presidents and CEOs; strong in entrepreneurship, biochemistry and international business; merit scholarships up to $30,000." },
  "WesternOR": { about: "A public university in Monmouth, Oregon — one of the most affordable for international students. Strong in education, IT and social work; small classes and a personal approach." },
  "Whittier":  { about: "A liberal arts college near Los Angeles, Richard Nixon’s alma mater. The unique Liberal Education and America’s Promise (LEAP) program; strong in business, film and law." },
  "Widener":   { about: "A private university in Chester, Pennsylvania, 15 minutes from Philadelphia and Delaware. An accredited law school; strong in engineering, nursing and business." },
  "Wilson":    { about: "One of the oldest women’s liberal arts colleges in the US, in Chambersburg, Pennsylvania. Among the first to admit non-traditional students; strong in veterinary technology and business." },
  "ColbySawyer": { about: "A liberal arts college in scenic New London, New Hampshire. A campus with a student farm; strong in design, nursing and business; an active outdoor culture." },
  "BridgewaterC": { about: "A Brethren liberal arts college in the Shenandoah Valley, Virginia. An Outdoor Recreation and Tourism Management program; strong in education, business and cross-cultural dialogue." },
  "DakotaWes":  { about: "A Methodist university in Mitchell, South Dakota. Small and cozy; strong in sports science, business and nursing; some of the lowest prices in the Midwest." },
  "CentralMeth": { about: "A Methodist university in Fayette, Missouri. One of the most affordable private schools in the US; strong in education, business and business communication; athletic scholarships." },
  "AuburnMont": { about: "An Auburn University campus in Alabama’s capital, Montgomery. Public-university prices with the Auburn brand degree; strong in business, law and education." },
  "Brescia":   { about: "A small Catholic university in Owensboro, Kentucky. One of the cheapest private schools in the US; strong in psychology, social work and education." },
};
