/* ============================================================
   UNIVERSITY DETAILS — ENGLISH descriptions.
   Keyed by `short` from catalog.jsx. Loaded after uni-data.js.
   uni-page.jsx picks this when __EA_LANG === 'en'; if a `short`
   is missing here, it falls back to a localized generated blurb.
   Only the `about` field is translated (facts come from uni-data.js).
   ============================================================ */
var EA_UNI_DETAILS_EN = {
  /* ========== ITALY ========== */
  "PoliMi":   { about: "Italy’s largest technical university and its leading school of engineering, architecture and design — consistently in the world’s top 20 for design and architecture." },
  "Bocconi":  { about: "A private Milan university and one of Europe’s strongest business schools. Economics, finance, management and law, with a powerful alumni network in global corporations." },
  "UniBo":    { about: "The oldest university in the Western world, running continuously since 1088. Strong in economics, law and the humanities, with campuses in five cities across the region." },
  "Sapienza": { about: "One of Europe’s largest universities and Rome’s main public institution. A world leader in classics and archaeology, with a wide choice of English-taught programs." },
  "UniPD":    { about: "One of the world’s oldest universities — Galileo once taught here. Strong in medicine, psychology and engineering, with a well-developed scholarship system for international students." },
  "CaFosc":   { about: "A university in the heart of Venice and Italy’s first school of commerce. Known for economics, languages and Asian studies; classes are held in historic palazzi on the canals." },
  "LUISS":    { about: "A prestigious private university in Rome backed by Confindustria, the Italian industry association. Law, political science and business, with close ties to employers." },
  "PoliTO":   { about: "A leading engineering school in Turin — home of FIAT and the Italian auto industry. Strong in automotive, aerospace and computer engineering." },
  "UniMi":    { about: "‘La Statale’, the largest university in Milan. A broad range of programs from law and medicine to the natural sciences; a member of the prestigious LERU research league." },
  "UniTO":    { about: "One of Italy’s largest classical universities. Strong in medicine, law and economics; its alumni include Nobel laureates and two of the country’s presidents." },
  "UniPI":    { about: "A historic university in Tuscany and Galileo Galilei’s alma mater. Today one of Italy’s strongest centres for computer science and physics." },
  "TorVerg":  { about: "A modern campus university in southern Rome. Strong in medicine, engineering and economics, and one of Italy’s leaders in English-taught programs." },
  "UniFI":    { about: "The classical university of Florence — the capital of the Renaissance. Especially strong in architecture, design, art history and agricultural sciences." },
  "UniSI":    { about: "One of Europe’s oldest universities, in the Tuscan town of Siena. A compact ‘university town’ with strong medicine, biotechnology and economics." },
  "UniPV":    { about: "An ancient university in Lombardy with an Oxbridge-style college system. Known for medicine and engineering — Alessandro Volta studied here." },
  "UniTN":    { about: "One of the highest-rated universities in Italy for teaching quality, regularly ranked #1 among the country’s mid-sized universities. Strong computer and cognitive science, with a campus in the Alps." },
  "UniTS":    { about: "A university in the port city of Trieste — Italy’s scientific capital, with the country’s largest concentration of research centres. Strong in physics and engineering." },
  "UniBS":    { about: "A public university in Lombardy with strong medicine and engineering. Brescia is an industrial hub, giving students direct access to internships." },
  "UniPR":    { about: "One of the world’s oldest universities, dating back to the 10th century. Known for medicine, pharmacy and food science — Parma is Italy’s gastronomic capital." },
  "LUMSA":    { about: "A Catholic private university in Rome, the city’s second-oldest non-state institution. Education, law and communications, with small groups and personal mentoring." },
  "Marang":   { about: "The legendary Milan school of fashion and design that produced Domenico Dolce and Franco Moschino. Campuses in the world’s fashion capitals and close ties to fashion houses." },
  "IULM":     { about: "A Milan university of communications, marketing and media. One of Italy’s main centres for training PR, translation and creative-industry specialists." },
  "UniMiB":   { about: "A young, dynamic Milan university with a modern campus in the Bicocca district. Strong in medicine, psychology and data science." },
  "UniGE":    { about: "A historic university in Italy’s largest port. Strong in marine engineering, robotics and economics, with campuses along the Ligurian coast." },
  "Roma3":    { about: "The youngest of Rome’s three public universities, which quickly became one of the country’s notable institutions. Strong in law, architecture and political science." },
  "UniPA":    { about: "Sicily’s main university, in Palermo. A wide choice of programs at some of the lowest tuition and living costs in Western Europe." },
  "UniME":    { about: "An old Sicilian university by the Strait of Messina. Strong in medicine, veterinary science and law, with affordable tuition and living costs." },
  "UniCT":    { about: "Sicily’s oldest university, at the foot of Mount Etna. Strong medicine and engineering — Catania is southern Italy’s main tech hub (‘Etna Valley’)." },
  "UniSA":    { about: "Heir to the medieval Salerno medical school — Europe’s first. A modern campus near Salerno, strong in engineering and computer science." },
  "UniCAS":   { about: "A compact public university between Rome and Naples. Affordable, with strong engineering and sports science and a welcoming environment for international students." },
  "UniUD":    { about: "A university in north-eastern Italy near Austria and Slovenia. Strong in business, winemaking and engineering, in the high-quality-of-life Friuli region." },
  "UniCamp":  { about: "A public university named after architect Luigi Vanvitelli in the Naples region. Known for medicine and architecture, with some of the lowest tuition in Italy." },
  "UniBa":    { about: "A large university in the capital of Apulia in southern Italy. A wide choice of fields — from law to agricultural sciences — at very affordable cost." },
  "UNIVPM":   { about: "A polytechnic university of the Marche region in seaside Ancona. Strong in engineering, medicine and economics, with small groups and a practical focus." },
  "LinkCU":   { about: "A private Rome university with an international focus and Foundation programs. Business, international relations and cinema, taught in English." },
  "RUFA":     { about: "The Rome University of Fine Arts — painting, graphic design, film and game art. Studios in Rome’s historic centre, taught by working artists." },
  "LUM":      { about: "A private university in Apulia with programs in business, law and medicine. Flexible admission and Foundation programs for international students." },

  /* ========== USA ========== */
  "Roosevelt": { about: "A university in a skyscraper in the heart of Chicago, named after Franklin and Eleanor Roosevelt. Generous merit scholarships for international students; strong in business and the performing arts." },
  "Bellevue":  { about: "One of Washington State’s largest colleges, right across from the Microsoft and Amazon campuses. A popular 2+2 route: two years here, then transfer to a top university." },
  "LaSalle":   { about: "A Catholic university in Philadelphia with a century and a half of history. Known for nursing, business and communications; the campus is 15 minutes from downtown." },
  "K-Zoo":     { about: "One of the oldest liberal arts colleges in the Midwest. Small classes, required internships and study abroad; a high share of graduates go on to master’s and PhD programs." },
  "Westcliff": { about: "A private university in Irvine, California — one of the safest cities in the US. Business and IT, flexible study formats and affordable-for-California tuition." },
  "UB":        { about: "The flagship and largest campus of New York’s SUNY system, a member of the prestigious AAU research association. Strong in engineering, medicine and computer science." },
  "UE":        { about: "A private university in Indiana with small classes and its own campus in England (Harlaxton College). Strong in engineering, physical therapy and theatre." },
  "DePaul":    { about: "The largest Catholic university in the US, in downtown Chicago. One of the country’s best for game design and film; a strong business school and computer science." },
  "Rowan":     { about: "A fast-growing public university in New Jersey, an hour from Philadelphia. A strong engineering school and two medical schools — rare for a university of its size." },
  "HarrisU":   { about: "A young STEM university in Pennsylvania’s capital. Science and technology only: data analytics, cybersecurity, biotech; practice- and employment-focused." },
  "UST":       { about: "A Catholic university in Houston’s museum district. Small classes, strong business and pre-med preparation; next to the world’s largest medical center." },
  "ASU":       { about: "One of the largest universities in the US, named the country’s most innovative university for years running. Top-tier engineering, business and journalism; a huge range of programs." },
  "CalState":  { about: "The largest public university system in the US — 23 campuses across California. Practice-oriented programs at affordable in-state cost." },
  "SJSU":      { about: "The oldest public university on the West Coast — in the heart of Silicon Valley. #1 in the US for graduates hired by Apple, Cisco and other tech giants." },
  "GGU":       { about: "A university in downtown San Francisco specialising in law, taxation and business for working professionals. Evening and flexible formats." },
  "MU":        { about: "A Catholic university in Arlington, Virginia — across the river from Washington. Strong in nursing, cybersecurity and interior design; internships in the capital." },
  "Adelphi":   { about: "Long Island’s first private university, 40 minutes from Manhattan. A green arboretum campus; strong in nursing, psychology and social work." },
  "UC":        { about: "The birthplace of co-op education: paid internships have been built into study since the 19th century. Top engineering, music (CCM) and design — DAAP is world-ranked." },
  "Temple":    { about: "A large research university in Philadelphia with some of the most affordable tuition among Northeast urban schools. Strong in business, law, film and media." },
  "Drexel":    { about: "A technology university in Philadelphia famous for its co-op system: up to three paid 6-month internships during the bachelor’s. Strong in engineering and design." },
  "Suffolk":   { about: "A university in the heart of Boston, opposite the State House. Known for law and business; internships a stone’s throw away in the city’s offices and courts." },
  "Pace":      { about: "A university with a campus by Wall Street in New York. A leader in finance and audit internships; strong in business, computer science and the performing arts." },
  "UArizona":  { about: "Arizona’s flagship university and an AAU member. A world leader in astronomy and space research — it takes part in NASA missions; strong in optics and medicine." },
  "FIU":       { about: "One of the largest public universities in the US, in Miami. Strong in international business, hospitality and engineering; the country’s most international city." },
  "UConn":     { about: "Connecticut’s flagship university, in the top 30 public schools in the US. Strong in business, engineering and pharmacy; between New York and Boston." },
  "Clarkson":  { about: "A private technology university in upstate New York. One of the best for return on a degree: engineering graduates quickly reach high salaries." },
  "ColChic":   { about: "The largest arts college in the US, in downtown Chicago. Film, music, fashion, game design, journalism; taught by working industry professionals." },
  "NYFA":      { about: "A film academy with campuses in New York and Los Angeles. Learning ‘through the camera’ from day one: directing, acting, animation and producing." },
  "Webster":   { about: "A university from St. Louis with campuses worldwide — from Vienna to Bangkok. Strong in international relations, business and media; you can switch campuses mid-study." },
  "Simmons":   { about: "A Boston university next to the Longwood medical cluster. Famous for nursing, nutrition and library science; the bachelor’s is women’s, the master’s is co-ed." },
  "FloridaTech": { about: "A technology university on Florida’s ‘Space Coast’, founded by NASA scientists at the dawn of the space age. Aerospace engineering, aviation, oceanography." },
  "NAU":       { about: "A young private university in Houston with some of the most affordable tuition in Texas. Computer science, business and education; a large international community." },
  "Radford":   { about: "A public university in the mountains of Virginia. Affordable, strong in nursing, forensic science and business; a safe campus town." },
  "Concord":   { about: "A small public university in West Virginia, known as ‘the campus beautiful’ for its mountain views. Low cost and personal attention from faculty." },
  "UAlbany":   { about: "One of the four flagship campuses of the SUNY system — in New York’s capital. Strong in criminology, public administration and cybersecurity." },
  "CWU":       { about: "A public university in central Washington. Known for aviation (its own flight fleet), music and business; a low cost of living." },
  "ConnColl":  { about: "A selective liberal arts college in New England with an arboretum campus on the sound. Generous financial aid, small classes and funded internships." },
  "SFBU":      { about: "A non-profit university in the San Francisco Bay Area, next to Silicon Valley. Computer science and business; substantial scholarships for nearly all admitted students." },
  "SCSS":      { about: "A university in Los Angeles with bachelor’s and master’s programs in business. Admission details are available at an Elite Academy consultation." },
  "DeAnza":    { about: "One of the best community colleges in the US — in Cupertino, Apple’s hometown. California’s leader in transfers to UC universities, including Berkeley and UCLA." },
  "GreenRiver":{ about: "A college near Seattle, one of the most international-student-friendly in the US. A well-established route to transfer to universities after two years." },
  "SCC":       { about: "A college in the heart of Seattle on Capitol Hill. A convenient start for the 2+2 route and English programs; the city is home to Amazon, Boeing and Starbucks." },
  "SMC":       { about: "The #1 college in the US for transfers to UCLA and USC. A campus 15 minutes from the ocean; strong in film, design and business." },
  "LACC":      { about: "A historic city college of Los Angeles in the Hollywood area. An affordable entry into California’s higher-education system; a well-known theatre school." },
  "CCC":       { about: "A network of seven city colleges of Chicago — one of the largest community-college districts in the US. Low cost and transfer agreements with Illinois universities." },
  "LWIT":      { about: "A technical institute in Kirkland, a Seattle suburb near the Google and Microsoft offices. Applied IT programs and an applied bachelor’s degree." },
  "CCSF":      { about: "San Francisco’s main city college. A huge choice of programs and a well-established transfer to California universities after two years." },
  "CSI":       { about: "A career school in Chicago with short, hands-on IT and business programs. A fast, low-cost way to earn a US certificate and experience." },
};
